import React, { Fragment } from "react";
import { EarthIcon, GiftIcon, ShareIcon } from "@/Components/Shared/Icons";
import Item from "./Item";
import HorizontalSeparatorLine from "./HorizontalSeparatorLine";
import { useMobile } from "@/hooks/useMobile";
import Image from "next/image";
interface ReferralProgramOverviewProps {
  activeSection: number;
  section: number;
}
const ReferralProgramOverview: React.FC<ReferralProgramOverviewProps> = ({ activeSection, section }) => {
  const { isMobile } = useMobile();

  if (activeSection !== section && isMobile) return;
  return (
    <Fragment>
      <div className="flex flex-col gap-[15px] px-[40px]">
        <p className="text-xl font-normal text-[#222222]">Share and Earn! 🚀✨</p>
        <p className="text-[15px] font-normal text-[#87878D]">
          Invite your friends and neighbours to SkyTrade. If they register and claim airspaces, you receive:
        </p>
        <div className="text-[15px] font-normal text-[#4285F4]">
          <ul className="list-disc pl-5">
            <li>
              You earn <span className="text-[20px] font-bold">+5 SKY Points</span> for each successful referral
              registration when your friend creates an account and claims a property.
            </li>
            <li>
              Your friend also gets <span className="text-[20px] font-bold">+5 SKY Points</span> upon creating an
              account and claiming a property.
            </li>
            <li>
              On top of that, you&apos;ll receive a fantastic bonus: <span className="text-[20px] font-bold">+10%</span>{" "}
              on top of the passive income generated by those you refer,{" "}
              <span className="text-[20px] font-bold">FOREVER!</span>
            </li>
          </ul>
        </div>
      </div>
      <div className="flex flex-col items-center justify-center gap-4 px-[35px] md:mt-6 md:flex-row md:gap-9 md:px-[51px]">
        <Item
          icon={<ShareIcon color={undefined} />}
          title={"Share"}
          text={"Send your invite link or code to your friends and explain them how cool is SkyTrade"}
        />
        <HorizontalSeparatorLine />
        <Item
          icon={<EarthIcon />}
          title={"Register & Claim"}
          text={"Let them register and claim their airspaces using your referral link or code"}
        />
        <HorizontalSeparatorLine />
        <Item
          icon={<GiftIcon />}
          title={"Earn"}
          text={"You and your friends are rewarded with 5 SKY points and more"}
        />
      </div>

      <div className="mt-10 flex h-full w-full items-center justify-center">
        <Image src={"/images/Sky_Trade_Infographi.svg"} alt="Infographi" width={1055} height={682} />
      </div>
    </Fragment>
  );
};
export default ReferralProgramOverview;
